server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: yaz307165


  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQL92Dialect
  show-sql: true
  properties:
    hibernate:
      temp:
      use_jdbc_metadata_defaults: true

  mail:
    host: smtp.qq.com #发送邮件服务器
    username: 3077161150@qq.com
    password: yzphbfbnpiogdfjb
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
#          port: 994 #设置端口465或者994
          timeout: 10000
          display:
            sendmail: aaa #可以任意
            sendname: bbb #可以任意
          smtp:
            starttls:
              enable: true
              required: true
            ssl:
              enable: true #开启SSL
    default-encoding: utf-8
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: ooadGroup
      lettuce:
        pool:
          max-idle: 8
          min-idle: 0
          max-wait: 100



