server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/campus?characterEncoding=utf8&useSSL=false
    username: root
    password: yaz307165

  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

  jpa:
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  show-sql: true
  properties:
    hibernate:
      temp:
      use_jdbc_metadata_defaults: true

  mail:
    host: smtp.qq.com #发送邮件服务器
    username: 3077161150@qq.com
    password: ------------
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
#          port: 994 #设置端口465或者994
          timeout: 10000
          display:
            sendmail: aaa #可以任意
            sendname: bbb #可以任意
          smtp:
            starttls:
              enable: true
              required: true
            ssl:
              enable: true #开启SSL
    default-encoding: utf-8
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: ooadGroup
      lettuce:
        pool:
          max-idle: 8
          min-idle: 0
          max-wait: 100



