server:
  port: 8082

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: yaz307165

#  redis:
#    host: 172.18.179.91
#    port: 6379
#    password: 307165
#    lettuce:
#      pool:
#        max-activate: 8;
#        max-idle: 8;
#        min-idle: 0;
#        max-wait: 100;
#
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQL92Dialect
  show-sql: true
  properties:
    hibernate:
      temp:
      use_jdbc_metadata_defaults: true

  mail:
    host: smtp.qq.com #发送邮件服务器
    username: 3077161150@qq.com
    password: jtfyksitqujudehd
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          port: 465 #设置端口465或者994
          timeout: 10000
          display:
            sendmail: aaa #可以任意
            sendname: bbb #可以任意
          smtp:
            starttls:
              enable: true
              required: true
            ssl:
              enable: true #开启SSL
    default-encoding: utf-8


    utils-config:
      jwt:
        header:Authentication
        expire:6048000
        secret:zyazzyaz


